export {initGame}
from './initGame.js';
export {receiveBoard}
from './receiveBoard.js';
export {openCell}
from './openCell.js';
export {receiveCell}
from './receiveCell.js';
export {boom}
from './boom.js';
export {showResult}
from './showResult.js';
export {setFlag}
from './setFlag.js';
